services:
  backend:
    build: ./backend
    container_name: backend
    
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend

    ports:
      - "5173:5173"

    env_file:
      - ./frontend/.env
    
    depends_on:
      - backend

  nginx:
    image: nginx:alpine

    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - frontend
      - backend